# _config.yml
remote_theme: just-the-docs/just-the-docs
title: Python spiekbrief
description: De Python spiekbrief van het jaar!
Author: Dietrich Janssens
site_favicon: favicon.ico

# Optional: to show a sidebar with a TOC
just_the_docs:
  search_enabled: true
  nav_enabled: false

# GitHub Pages settings
plugins:
  - jekyll-seo-tag
