# _config.yml
remote_theme: just-the-docs/just-the-docs
title: Python spiekbrief
description: De Python spiekbrief van het jaar!
Author: Dietrich Janssens
site_favicon: favicon.ico

# Optional: to show a sidebar with a TOC
just_the_docs:
  logo: "logo.png" # you can set your own logo path
  search_enabled: true
  show_sidebar: true
  collections:
    pages:
      output: true  

# GitHub Pages settings
plugins:
  - jekyll-seo-tag
