# _config.yml
remote_theme: just-the-docs/just-the-docs
title: Python spiekbrief
description: De Python spiekbrief van het jaar!
Author: Dietrich Janssens
site_favicon: favicon.ico

nav_enabled: false
search_enabled: true

# GitHub Pages settings
plugins:
  - jekyll-seo-tag
